### ISSUE TITLE
About nuScenes dataset

### ISSUE THREAD

**Issue by oliver0922** [Ruiyang-061X/LiSe#2]
Thank you for your nice work!
Do you have any plan for releasing the code for nuScenes dataset?

**Comment by Ruiyang-061X** [comment]
Thank you for your interest in our work! We are currently organizing the code for the nuScenes dataset, and it will be released once it is ready. In the meantime, I recommend running experiments on the Lyft dataset, which is only around 80GB and requires less storage, while the nuScenes dataset is over 300GB.
