### ISSUE TITLE
Generate Pseudo Labels on Nuscenes

### ISSUE THREAD

**Issue by ZSA010807** [Ruiyang-061X/LiSe#4]
Hello， @Ruiyang-061X 
Thanks for your great work. Do you have any plans to release the code for generating Pseudo Labels on nuscenes?

**Comment by Ruiyang-061X** [comment]
Thank you for your interest in our work! We are currently organizing the code for pseudo box generation on nuScenes and will release it once this process is complete. In the meantime, we recommend trying the Lyft pseudo box generation first, as it requires only 80 GB of storage, whereas nuScenes requires over 300 GB.
